version: "3.7"

volumes:
  db:

services:
  proxy:
    image: nginx:1-alpine
    ports:
      - "1236:1236"
      - "8536:8536"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro,Z
    restart: always
    depends_on:
      - pictrs
      - lemmy-ui

  sublinks:
    image: ghcr.io/sublinks/sublinks-api:0.0.1-snapshot
    restart: always
    ports:
      - "8080:8080"
    environment:
      SUBLINKS_DB_URL: jdbc:mysql://db:3306/sublinks
      SUBLINKS_DB_USERNAME: sublinks
      SUBLINKS_DB_PASSWORD: sublinks
      SUBLINKS_JWT_SECRET: cHVkZGluLXdpbnN0b24taXJpcy1hcnlhLWZpbm4tcGlja2xlcy1jaGVlc2UtYm9vYnM=
      SUBLINKS_BASE_URL: https://demo.sublinks.org
      SUBLINKS_PICTRS_URL: http://pictrs:8080
    depends_on:
      - db
      - pictrs
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sublinks
      - MYSQL_USER=sublinks
      - MYSQL_PASSWORD=sublinks
    volumes:
      - db:/var/lib/mysql
    restart: always

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.0-rc.11
    environment:
      #- LEMMY_UI_DEBUG=true
      - LEMMY_UI_DISABLE_CSP=true
      - LEMMY_UI_LEMMY_INTERNAL_HOST=sublinks:8080
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=demo.sublinks.org
    restart: always
    depends_on:
      - sublinks

  pictrs:
    image: docker.io/asonix/pictrs:0.4.3
    hostname: pictrs
    user: 991:991
    restart: always
