version: "3.7"

volumes:
  db_data:
  pictrs_data:

services:
  proxy:
    image: nginx:1-alpine
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro,Z
    restart: always
    depends_on:
      - pictrs
      - sublinks-ui

  sublinks:
    image: ghcr.io/sublinks/sublinks-api:0.0.1-snapshot
    restart: always
    environment:
      SUBLINKS_DB_URL: jdbc:mysql://db:3306/sublinks
      SUBLINKS_DB_USERNAME: sublinks
      SUBLINKS_DB_PASSWORD: sublinks
      SUBLINKS_JWT_SECRET: cHVkZGluLXdpbnN0b24taXJpcy1hcnlhLWZpbm4tcGlja2xlcy1jaGVlc2UtYm9vYnM=
      SUBLINKS_BASE_URL: http://sublinks:8080
      SUBLINKS_PICTRS_URL: http://pictrs:8080
      FEDERATION_QUEUE_HOST: queue
      FEDERATION_QUEUE_PORT: 5672
      FEDERATION_QUEUE_USER: sublinks
      FEDERATION_QUEUE_PASS: sublinks
      FEDERATION_QUEUE_NAME: federation
      FEDERATION_EXCHANGE_NAME: federation
      BACKEND_QUEUE_NAME: backend
      BACKEND_TOPIC_NAME: backend
    depends_on:
      - db
      - pictrs
      - queue

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sublinks
      - MYSQL_USER=sublinks
      - MYSQL_PASSWORD=sublinks
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  sublinks-ui:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../../.:/app/.
      - /app/node_modules/
    command: sh -c "npm i && npm run dev"
    environment:
      - NEXT_PUBLIC_SUBLINKS_API_BASE_URL=sublinks:8080
      - WATCHPACK_POLLING=true
    restart: always
    depends_on:
      - sublinks

  seeder:
    image: node:20-alpine
    working_dir: /job
    volumes:
      - ./seeder/.:/job/.
    command: sh -c "npm i && npm run seed"
    environment:
      - NEXT_PUBLIC_SUBLINKS_API_BASE_URL=sublinks:8080
    depends_on:
      - db
      - sublinks

  pictrs:
    image: docker.io/asonix/pictrs:0.4.7
    hostname: pictrs
    environment:
      - PICTRS_OPENTELEMETRY_URL=http://otel:4137
      - PICTRS__MEDIA__VIDEO_CODEC=vp9
      - PICTRS__MEDIA__GIF__MAX_WIDTH=256
      - PICTRS__MEDIA__GIF__MAX_HEIGHT=256
      - PICTRS__MEDIA__GIF__MAX_AREA=65536
      - PICTRS__MEDIA__GIF__MAX_FRAME_COUNT=400
    volumes:
      - pictrs_data:/mnt:Z
    user: 991:991
    restart: always

  queue:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=sublinks
      - RABBITMQ_DEFAULT_PASS=sublinks
    ports:
      - "15672:15672"
      - "5672:5672"
